package io.axiom.editor.ui.theme

import androidx.compose.ui.graphics.Color

// ---------- Light palette ----------
val LightPrimary = Color(0xFF1A6FE8)
val LightOnPrimary = Color(0xFFFFFFFF)
val LightPrimaryContainer = Color(0xFFD6E4FF)
val LightOnPrimaryContainer = Color(0xFF00204D)

val LightSecondary = Color(0xFF4F6585)
val LightOnSecondary = Color(0xFFFFFFFF)
val LightSecondaryContainer = Color(0xFFD5E3FF)
val LightOnSecondaryContainer = Color(0xFF0C1D35)

val LightTertiary = Color(0xFF1E8A6E)
val LightOnTertiary = Color(0xFFFFFFFF)
val LightTertiaryContainer = Color(0xFFB2F0DF)
val LightOnTertiaryContainer = Color(0xFF002B21)

val LightBackground = Color(0xFFF4F6FA)
val LightOnBackground = Color(0xFF191C20)
val LightSurface = Color(0xFFFFFFFF)
val LightOnSurface = Color(0xFF191C20)
val LightSurfaceVariant = Color(0xFFE1E4EC)
val LightOnSurfaceVariant = Color(0xFF44474F)
val LightSurfaceContainerLow = Color(0xFFFFFFFF)
val LightSurfaceContainerHigh = Color(0xFFE8ECF4)
val LightOutline = Color(0xFF74777F)
val LightError = Color(0xFFBA1A1A)
val LightOnError = Color(0xFFFFFFFF)

// ---------- Dark palette ----------
val DarkPrimary = Color(0xFF6EAAFF)
val DarkOnPrimary = Color(0xFF003062)
val DarkPrimaryContainer = Color(0xFF0A4A9A)
val DarkOnPrimaryContainer = Color(0xFFD6E4FF)

val DarkSecondary = Color(0xFF8FAACC)
val DarkOnSecondary = Color(0xFF1C2F47)
val DarkSecondaryContainer = Color(0xFF2A3F58)
val DarkOnSecondaryContainer = Color(0xFFD5E3FF)

val DarkTertiary = Color(0xFF4FD8B6)
val DarkOnTertiary = Color(0xFF00382A)
val DarkTertiaryContainer = Color(0xFF005140)
val DarkOnTertiaryContainer = Color(0xFFB2F0DF)

val DarkBackground = Color(0xFF10131A)
val DarkOnBackground = Color(0xFFE2E3EA)
val DarkSurface = Color(0xFF10131A)
val DarkOnSurface = Color(0xFFE2E3EA)
val DarkSurfaceVariant = Color(0xFF282C38)
val DarkOnSurfaceVariant = Color(0xFF9EA3B0)
val DarkSurfaceContainerLow = Color(0xFF1A1E29)
val DarkSurfaceContainerHigh = Color(0xFF252934)
val DarkOutline = Color(0xFF585D6A)
val DarkError = Color(0xFFFFB4AB)
val DarkOnError = Color(0xFF690005)

// ---------- GitHub screen — light token colors ----------
val GhLightBackground       = Color(0xFFECEEF8)
val GhLightCard             = Color(0xFFFFFFFF)
val GhLightCardExpanded     = Color(0xFFE2ECFC)
val GhLightExpandedBorder   = Color(0xFFB8CFFB)
val GhLightInput            = Color(0xFFFFFFFF)
val GhLightActionBtn        = Color(0xFFD5E6FF)
val GhLightCommitWrap       = Color(0x0A1A6FE8)
val GhLightTextPrimary      = Color(0xFF1A1C2E)
val GhLightTextSecondary    = Color(0xFF6B7199)
val GhLightTextMuted        = Color(0xFF9096B8)
val GhLightTextMutedLight   = Color(0xFF6B7199)
val GhLightAccentBlue       = Color(0xFF1A6FE8)
val GhLightAccentBlueLight  = Color(0xFF1A6FE8)
val GhLightAccentRed        = Color(0xFFCF6679)
val GhLightAccentGreen      = Color(0xFF107C41)
val GhLightAccentBlueAlpha  = Color(0x331A6FE8)
val GhLightAccentRedAlpha   = Color(0x22EF5350)
val GhLightAccentBlueAlpha2 = Color(0x221A6FE8)
val GhLightPlaceholder      = Color(0xFF9096B8)
val GhLightLoginBorder      = Color(0x221A6FE8)

// ---------- GitHub screen — dark token colors ----------
val GhDarkBackground       = Color(0xFF0F111A)
val GhDarkCard             = Color(0xFF1A1D30)
val GhDarkCardExpanded     = Color(0xFF1D213A)
val GhDarkExpandedBorder   = Color(0x4D2160C4)
val GhDarkInput            = Color(0xFF252942)
val GhDarkActionBtn        = Color(0xFF252942)
val GhDarkCommitWrap       = Color(0x26000000)
val GhDarkTextPrimary      = Color(0xFFFFFFFF)
val GhDarkTextSecondary    = Color(0xFF7C82A6)
val GhDarkTextMuted        = Color(0xFF4A517A)
val GhDarkTextMutedLight   = Color(0xFFA0A5C4)
val GhDarkAccentBlue       = Color(0xFF2160C4)
val GhDarkAccentBlueLight  = Color(0xFF4C8BF5)
val GhDarkAccentRed        = Color(0xFFCF6679)
val GhDarkAccentGreen      = Color(0xFF107C41)
val GhDarkAccentBlueAlpha  = Color(0x4D2160C4)
val GhDarkAccentRedAlpha   = Color(0x26EF5350)
val GhDarkAccentBlueAlpha2 = Color(0x264C8BF5)
val GhDarkPlaceholder      = Color(0xFF52587A)
val GhDarkLoginBorder      = Color(0x0DFFFFFF)
